services:
  roommates-helper:
    build: .
    container_name: roommates-helper
    restart: unless-stopped
    volumes:
      - ./roommates_roles.txt:/usr/src/app/roommates_roles.txt
      - ./verification_config.json:/usr/src/app/verification_config.json:rw
      - ./message_logger_config.json:/usr/src/app/message_logger_config.json:rw
      - ./infractions.json:/usr/src/app/infractions.json:rw
      - ./health.json:/usr/src/app/health.json:rw
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "node", "dist/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: roommates-helper-network
