version: '3.8'

services:
  roommates-helper:
    build: .
    container_name: roommates-helper
    restart: unless-stopped
    volumes:
      - ./roommates_roles.txt:/usr/src/app/roommates_roles.txt
      - ./verification_config.json:/usr/src/app/verification_config.json
      - ./health.json:/usr/src/app/health.json
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "node", "dist/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
